### ISSUE TITLE
Add support for chatgpt-4o-latest

### ISSUE THREAD

**Issue by ghost-ng** [WP-Autoplugin/wp-autoplugin#3]
I added chatgpt-4o-latest into the source code to work with my openai api key, but I am running into a formatting issue.

This is being generated at the top and bottom of the php code:

```
```(3 tick marks) php
<?php
...
...
?>
``` (3 tick marks)
```

**Comment by balazsrm** [comment]
Hi @ghost-ng I've just updated the plugin and added the `chatgpt-4o-latest` model.

The tick marks appearing is because the model responds with Markdown formatting, even though it is instructed to not do that in the prompt. Here's what you can do:

A. Try again the code generation step.
B. Switch to a different model (I recommend Claude 3.5 Sonnet) and try with that.
C. Edit the code manually in the last step before activating the plugin.
D. Adjust the prompt to emphasize that Markdown is not allowed.

Hope that helps!

**Comment by ghost-ng** [comment]
yea ive been editting the code manually to remove the ticks if they are there - I've also noticed on my own work that the gpt for some reason cannot understand formatting rules very well.
